name: super_salao_pro
description: App de gestão de salão
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#6A11CB"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"